# site settings
title: Cloud
subtitle: Commit
email: contact@cloudcommit.co
description: Make your organization cloud native. Scale as much as your customers want you to.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cloudcommit.co # the base hostname & protocol for your site
author:
street_address:
city: Abu Dhabi
state:
zip_code:
country: United Arab Emirates
phone: +971 505659644

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/cloudcommitco
github_url: https://github.com/cloudcommitco
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

formspree_code: mjvwdzak

# build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

permalink: pretty
